return {
    "lua_ls",
    "pyright",
    "clangd",
    -- "codelldb",
    "cmake",
    -- "cmakelang",
    -- "cmakelint",
    "bashls",
    -- "svls",
    -- "asm_lsp",
    "vimls",
    "marksman",
    "sqlls",
    -- "texlab",
    "jsonls",
    -- "tsserver",
    "tailwindcss",
    "eslint",
    -- "gopls",
    -- "golangci_lint_ls",
}
