return {
    "lua_ls",
    "stylua",
    "pyright",
    -- "flake8",
    "clangd",
    -- "codelldb",
    -- "clang_format",
    "cmake",
    -- "cmakelang",
    -- "cmakelint",
    -- "codespell",
    "bashls",
    "svls",
    -- "asm_lsp",
    "vimls",
    "marksman",
    "sqlls",
    -- "texlab",
    "jsonls",
    "tsserver",
    "tailwindcss",
    "prettier",
    "eslint",
}
